### ISSUE TITLE
13.08.2024 keine Daten?

### ISSUE THREAD

**Issue by HorstErnst** [robert-koch-institut/Intensivkapazitaeten_und_COVID-19-Intensivbettenbelegung_in_Deutschland#14]
Für heute wurden keine Daten zur Intensivbettenbelegung gemeldet. Wird das nun nachgeholt oder eingestellt?

**Comment by RKIOpenData** [comment]
Hallo @HorstErnst,

das wird nachgeholt. Wir haben gerade kleinere technische Schwierigkeiten, deshalb liegen die Daten von gestern noch nicht vor. Wir hoffen diese im Laufe des Tages beheben zu können.

Viele Grüße
Simon Scholler | RKI Open Data Team

**Comment by BugBoomBang** [comment]
Hallo, die Daten für den 13.08.2024 sind jetzt verfügbar.
Viele Grüße
Simon Scholler | RKI Open Data Team

**Comment by RKIOpenData** [comment]
Hallo, die Daten für den 13.08.2024 sind jetzt verfügbar.
Viele Grüße
Simon Scholler | RKI Open Data Team
