### ISSUE TITLE
28.8.24: Update fehlt

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/Intensivkapazitaeten_und_COVID-19-Intensivbettenbelegung_in_Deutschland#15]

**Comment by RKIOpenData** [comment]
Danke, haben wir auf dem Schirm und kümmern uns darum. Zum Hintergrund: Es gab Fehler in den Daten, deshalb wurde der Datensatz gestern nicht veröffentlicht. Dies wird nun geprüft.
Viele Grüße
RKI Open Data Team

**Comment by HorstErnst** [comment]
Gut zu wissen, dass die Daten auf Fehler geprüft werden! Hoffen wir, dass die Fehlerquelle gefunden und abgestellt wird.

**Comment by RKIOpenData** [comment]
Kurzes Update hierzu: Die Daten sind nun aktualisiert.
Viele Grüße
Simon | RKI Open Data Team
