### ISSUE TITLE
Keine Datenaktualisierung am 18. September 2024

### ISSUE THREAD

**Issue by RKIOpenData** [robert-koch-institut/Intensivkapazitaeten_und_COVID-19-Intensivbettenbelegung_in_Deutschland#18]
Liebe Nutzer:innen,
es gibt aktuell Probleme in der Datenbereitstellung in diesem Github Repo. Wir arbeiten daran, dies so schnell wie möglich zu beheben.
Viele Grüße,
RKI Open Data Team

**Comment by Rutger265** [comment]
Danke für's schnelle Behben der Probleme!

**Comment by RKIOpenData** [comment]
Danke und gerne. 
Eine kurze Info: Wir haben allerdings aktuell intern gerade Probleme bei der Datenbereitstellung, es kann dadurch in den nächsten Tagen zu Ausfällen bei der Datenbereitstellung kommen, dies nur schon mal vorab als Hinweis.
Viele Grüße,
RKI Open Data Team
