### ISSUE TITLE
Update fehlt seit dem 27.9.

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/Intensivkapazitaeten_und_COVID-19-Intensivbettenbelegung_in_Deutschland#20]

**Comment by HannesWuensche** [comment]
Lieber @Rutger265,

vielen Dank für den Hinweis. Leider kommt es manchmal zu Unregelmäßigkeiten. 
Die Daten sollten heute wie gewohnt wieder bereitgestellt werden. 

Mit besten Grüßen
@HannesWuensche 
für das Team | RKI Open Data
