### ISSUE TITLE
Fehlende Daten am 2.10.2024 und potentiell auch in den nächsten Tagen

### ISSUE THREAD

**Issue by RKIOpenData** [robert-koch-institut/Intensivkapazitaeten_und_COVID-19-Intensivbettenbelegung_in_Deutschland#21]
Liebe Nutzer:innen,

eine kurzer Hinweis: Es gibt aktuell Probleme bei der Datenbereitstellung. Da die Daten bei Inkonsistenzen nicht akualisiert werden, können heute keine neuen Daten bereitgestellt werden. Evtl. bleibt dieses Problem auch in den nächsten Tagen bestehen.

Entschuldigung für die Umstände und viele Grüße,
Simon | RKI Open Data Team

**Comment by Rutger265** [comment]
Danke, Simon für die Mitteilung!  
Stimmen die Daten der Zeitreihen im Intensivregister denn? (Leider kann man da die Nachmeldungen nicht ablesen.)

Grüße, Rutger

**Comment by RKIOpenData** [comment]
Hallo Rutger,

ich hab hierzu nochmal intern nachgefragt: Wir gehen davon aus, dass die Daten im Intensivregister korrekt sind, prüfen dies aber aktuell nochmal.

Viele Grüße
Simon | RKI Open Data Team

**Comment by HorstErnst** [comment]
Vermutlich gilt das auch für den 01.11., oder?

**Comment by SimonScholler** [comment]
Ja genau, es gibt aktuell Probleme bei der Datenbereitstellung in diesem Github Repo. Wir arbeiten daran, dies so schnell wie möglich zu beheben. Wir hoffen, dass wir heute wieder die aktuellen Daten bereitstellen können.
Viele Grüße, 
Simon | RKI Open Data Team

**Comment by SimonScholler** [comment]
Update: Die Daten sind jetzt wieder verfügbar.

Viele Grüße
Simon | RKI Open Data Team

**Comment by HorstErnst** [comment]
Vielen Dank!
