### ISSUE TITLE
Update July 20 is missing

### ISSUE THREAD

**Issue by Rutger265** [robert-koch-institut/Intensivkapazitaeten_und_COVID-19-Intensivbettenbelegung_in_Deutschland#7]

**Comment by RKIOpenData** [comment]
Hallo @Rutger265,

danke für die Info. Gestern gab es leider Probleme beim Hochladen der Daten. Heute hat der Upload wieder ordnungsgemäß geklappt.

viele Grüße
Knut Perseke
für das Team RKIOpenData
